### ISSUE TITLE
预训练文件错误

### ISSUE THREAD

**Issue by dsx4602** [zejunwang1/bertorch#3]
上传的huggingface预训练文件中，[simcse-tiny-chinese-wiki](https://huggingface.co/WangZeJun/simcse-tiny-chinese-wiki/blob/main/pytorch_model.bin)与[batchneg-tiny-chinese](https://huggingface.co/WangZeJun/batchneg-tiny-chinese/blob/main/pytorch_model.bin)的bin文件是一样的，是不是有哪个传错了？

**Comment by zejunwang1** [comment]
> 上传的huggingface预训练文件中，[simcse-tiny-chinese-wiki](https://huggingface.co/WangZeJun/simcse-tiny-chinese-wiki/blob/main/pytorch_model.bin)与[batchneg-tiny-chinese](https://huggingface.co/WangZeJun/batchneg-tiny-chinese/blob/main/pytorch_model.bin)的bin文件是一样的，是不是有哪个传错了？

是上传重复了，刚刚更新了。也可以用项目中提供的数据和命令重新进行训练。

**Comment by dsx4602** [comment]
> > 上传的huggingface预训练文件中，[simcse-tiny-chinese-wiki](https://huggingface.co/WangZeJun/simcse-tiny-chinese-wiki/blob/main/pytorch_model.bin)与[batchneg-tiny-chinese](https://huggingface.co/WangZeJun/batchneg-tiny-chinese/blob/main/pytorch_model.bin)的bin文件是一样的，是不是有哪个传错了？
> 
> 是上传重复了，刚刚更新了。也可以用项目中提供的数据和命令重新进行训练。

看到了，谢谢
